-- Tabela ALUNOS
CREATE TABLE public.alunos (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    email varchar(255) NOT NULL,
    nascimento date NULL,
    nome varchar(255) NOT NULL,
    telefone varchar(255) NULL,
    CONSTRAINT alunos_pkey PRIMARY KEY (id),
    CONSTRAINT ukmbvpvjdhy6gsmbw6odlro3ub UNIQUE (email)
);

-- Tabela EQUIPAMENTO
CREATE TABLE public.equipamento (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    marca varchar(255) NULL,
    nome_equipamento varchar(255) NOT NULL,
    quantidade int4 NULL,
    status varchar(255) NOT NULL,
    CONSTRAINT equipamento_pkey PRIMARY KEY (id)
);

-- Tabela PLANO DE AULAS
CREATE TABLE public.plano_de_aula (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    descricao varchar(255) NULL,
    duracao float4 NULL,
    nome varchar(255) NULL,
    nivel varchar(255) NULL,
    CONSTRAINT plano_de_aula_pkey PRIMARY KEY (id)
);

-- Tabela MANUTENÇÃO
CREATE TABLE public.manutencao (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    "data" date NULL,
    descricao varchar(255) NULL,
    equipamento_id int8 NULL,
    CONSTRAINT manutencao_pkey PRIMARY KEY (id),
    CONSTRAINT fk_manutencao_equipamento FOREIGN KEY (equipamento_id) REFERENCES public.equipamento(id)
);

-- Tabela MEMBROS
CREATE TABLE public.membros (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    data_fim date NULL,
    data_inicio date NULL,
    aluno_id int8 NOT NULL,
    plano_aula_id int8 NOT NULL,
    CONSTRAINT membros_pkey PRIMARY KEY (id),
    CONSTRAINT fk_membros_aluno FOREIGN KEY (aluno_id) REFERENCES public.alunos(id),
    CONSTRAINT fk_membros_plano_de_aula FOREIGN KEY (plano_aula_id) REFERENCES public.plano_de_aula(id)
);

-- Tabela TREINO
CREATE TABLE public.treino (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    descricao varchar(255) NULL,
    duracao float4 NULL,
    nivel int4 NULL,
    nome varchar(255) NULL,
    CONSTRAINT treino_pkey PRIMARY KEY (id)
);
